apiVersion: v1
kind: Service
metadata:
  name: webapp-api-lb
  namespace: webapp
spec:
  selector:
    app: webapp-api
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  type: LoadBalancer

